#!/usr/bin/env Rscript
re <- "^[a-z]+_([0-9]+\\.){3}(tgz|zip)$"
files <- dir("incoming", re, full.names = TRUE)
for (f in files) {
  drat:::insert(f, ".")
  unlink(f)
}

re <- "^[a-z]+_([0-9]+\\.){2}[0-9]+_oldrel.(tgz|zip)$"
files <- dir("incoming", re, full.names = TRUE)
for (f in files) {
  g <- sub("_oldrel\\.", ".", f)
  file.rename(f, g)
  drat:::insert(g, ".")
  unlink(g)
}


if (length(dir("incoming")) != 0) {
  stop("Unprocessed files in incoming")
}
